# Generated by Django 5.2 on 2025-06-25 00:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SepaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('sender_iban', models.CharField(max_length=34)),
                ('recipient_iban', models.CharField(max_length=34)),
                ('recipient_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('RJCT', 'RJCT'), ('RCVD', 'RCVD'), ('ACCP', 'ACCP'), ('ACTP', 'ACTP'), ('ACSP', 'ACSP'), ('ACWC', 'ACWC'), ('ACWP', 'ACWP'), ('ACCC', 'ACCC'), ('CANC', 'CANC'), ('PDNG', 'PDNG')], default='PDNG', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('source_account', models.CharField(max_length=50)),
                ('destination_account', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('local_iban', models.CharField(max_length=34)),
                ('account', models.CharField(max_length=255)),
                ('beneficiary_iban', models.CharField(max_length=34)),
                ('transfer_type', models.CharField(blank=True, choices=[('standard', 'Standard'), ('instant', 'Instant')], max_length=20, null=True)),
                ('type_strategy', models.CharField(choices=[('standard_only', 'Standard Only'), ('instant_only', 'Instant Only'), ('instant_if_available', 'Instant If Available')], max_length=20)),
                ('status', models.CharField(choices=[('RJCT', 'RJCT'), ('RCVD', 'RCVD'), ('ACCP', 'ACCP'), ('ACTP', 'ACTP'), ('ACSP', 'ACSP'), ('ACWC', 'ACWC'), ('ACWP', 'ACWP'), ('ACCC', 'ACCC'), ('CANC', 'CANC'), ('PDNG', 'PDNG')], default='PDNG', max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('end_to_end_id', models.CharField(blank=True, max_length=35, null=True)),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('custom_id', models.CharField(blank=True, max_length=256, null=True)),
                ('custom_metadata', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEPA2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RJCT', 'RJCT'), ('RCVD', 'RCVD'), ('ACCP', 'ACCP'), ('ACTP', 'ACTP'), ('ACSP', 'ACSP'), ('ACWC', 'ACWC'), ('ACWP', 'ACWP'), ('ACCC', 'ACCC'), ('CANC', 'CANC'), ('PDNG', 'PDNG')], default='PDNG', max_length=20)),
                ('purpose_code', models.CharField(blank=True, max_length=4, null=True)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('custom_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('end_to_end_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('account_name', models.CharField(choices=[('---', '---'), ('MIRYA TRADING CO LTD', 'MIRYA TRADING CO LTD'), ('ZAIBATSUS.L.', 'ZAIBATSUS.L.'), ('ELIZABETH GARDEN GROUP S.L.', 'ELIZABETH GARDEN GROUP S.L.'), ('REVSTAR GLOBAL INTERNATIONAL LTD', 'REVSTAR GLOBAL INTERNATIONAL LTD'), ('ECLIPS CORPORATION LTD.', 'ECLIPS CORPORATION LTD.'), ('CDG SYSTEM LTD', 'CDG SYSTEM LTD'), ('BFP FINANCE SERVICE S.L.', 'BFP FINANCE SERVICE S.L.'), ('MOHAMMAD REZA NAJAFI KALASHI', 'MOHAMMAD REZA NAJAFI KALASHI'), ('SERVICES ET PUBLICITÉ ONLINE LTD', 'SERVICES ET PUBLICITÉ ONLINE LTD'), ('XXX', 'XXX')], max_length=50)),
                ('account_iban', models.CharField(choices=[('---', '---'), ('DE86500700100925993805', 'DE86500700100925993805'), ('ES3901821250410201520178', 'ES3901821250410201520178'), ('ES7901824036500201650056', 'ES7901824036500201650056'), ('GB69BUKB20041558708288', 'GB69BUKB20041558708288'), ('GB43HBUK40127669998520', 'GB43HBUK40127669998520'), ('DE64202208000053288296', 'DE64202208000053288296'), ('ES5868880001643861269006', 'ES5868880001643861269006'), ('DE41400501500154813455', 'DE41400501500154813455'), ('GB33REVO00996939552283', 'GB33REVO00996939552283'), ('XXX', 'XXX')], max_length=24)),
                ('account_bic', models.CharField(choices=[('---', '---'), ('DEUTDEFFXXX', 'DEUTDEFFXXX'), ('BBVAESMMXXX', 'BBVAESMMXXX'), ('BUKBGB22XXX', 'BUKBGB22XXX'), ('HBUKGB4BXXX', 'HBUKGB4BXXX'), ('SXPYDEHHXXX', 'SXPYDEHHXXX'), ('QNTOESB2XXX', 'QNTOESB2XXX'), ('WELADED1MST', 'WELADED1MST'), ('REVOGB21XXX', 'REVOGB21XXX'), ('XXX', 'XXX')], max_length=11)),
                ('account_bank', models.CharField(choices=[('---', '---'), ('DEUTSCHE BANK AG', 'DEUTSCHE BANK AG'), ('BANCO BILBAO VIZCAYA ARGENTARIA S.A.', 'BANCO BILBAO VIZCAYA ARGENTARIA S.A.'), ('BARCLAYS BANK UK PLC', 'BARCLAYS BANK UK PLC'), ('HSBC UK BANK PLC', 'HSBC UK BANK PLC'), ('BANKING CIRCLE', 'BANKING CIRCLE'), ('OLINDA SAS SUCURSAL EN ESPAÑA', 'OLINDA SAS SUCURSAL EN ESPAÑA'), ('SPARKASSE MÜNSTERLAND OST', 'SPARKASSE MÜNSTERLAND OST'), ('REVOLUT LIMITED', 'REVOLUT LIMITED'), ('XXX', 'XXX')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('beneficiary_name', models.CharField(choices=[('---', '---'), ('MIRYA TRADING CO LTD', 'MIRYA TRADING CO LTD'), ('ZAIBATSUS.L.', 'ZAIBATSUS.L.'), ('ELIZABETH GARDEN GROUP S.L.', 'ELIZABETH GARDEN GROUP S.L.'), ('REVSTAR GLOBAL INTERNATIONAL LTD', 'REVSTAR GLOBAL INTERNATIONAL LTD'), ('ECLIPS CORPORATION LTD.', 'ECLIPS CORPORATION LTD.'), ('CDG SYSTEM LTD', 'CDG SYSTEM LTD'), ('BFP FINANCE SERVICE S.L.', 'BFP FINANCE SERVICE S.L.'), ('MOHAMMAD REZA NAJAFI KALASHI', 'MOHAMMAD REZA NAJAFI KALASHI'), ('SERVICES ET PUBLICITÉ ONLINE LTD', 'SERVICES ET PUBLICITÉ ONLINE LTD'), ('XXX', 'XXX')], max_length=50)),
                ('beneficiary_iban', models.CharField(choices=[('---', '---'), ('DE86500700100925993805', 'DE86500700100925993805'), ('ES3901821250410201520178', 'ES3901821250410201520178'), ('ES7901824036500201650056', 'ES7901824036500201650056'), ('GB69BUKB20041558708288', 'GB69BUKB20041558708288'), ('GB43HBUK40127669998520', 'GB43HBUK40127669998520'), ('DE64202208000053288296', 'DE64202208000053288296'), ('ES5868880001643861269006', 'ES5868880001643861269006'), ('DE41400501500154813455', 'DE41400501500154813455'), ('GB33REVO00996939552283', 'GB33REVO00996939552283'), ('XXX', 'XXX')], max_length=24)),
                ('beneficiary_bic', models.CharField(choices=[('---', '---'), ('DEUTDEFFXXX', 'DEUTDEFFXXX'), ('BBVAESMMXXX', 'BBVAESMMXXX'), ('BUKBGB22XXX', 'BUKBGB22XXX'), ('HBUKGB4BXXX', 'HBUKGB4BXXX'), ('SXPYDEHHXXX', 'SXPYDEHHXXX'), ('QNTOESB2XXX', 'QNTOESB2XXX'), ('WELADED1MST', 'WELADED1MST'), ('REVOGB21XXX', 'REVOGB21XXX'), ('XXX', 'XXX')], max_length=11)),
                ('beneficiary_bank', models.CharField(choices=[('---', '---'), ('DEUTSCHE BANK AG', 'DEUTSCHE BANK AG'), ('BANCO BILBAO VIZCAYA ARGENTARIA S.A.', 'BANCO BILBAO VIZCAYA ARGENTARIA S.A.'), ('BARCLAYS BANK UK PLC', 'BARCLAYS BANK UK PLC'), ('HSBC UK BANK PLC', 'HSBC UK BANK PLC'), ('BANKING CIRCLE', 'BANKING CIRCLE'), ('OLINDA SAS SUCURSAL EN ESPAÑA', 'OLINDA SAS SUCURSAL EN ESPAÑA'), ('SPARKASSE MÜNSTERLAND OST', 'SPARKASSE MÜNSTERLAND OST'), ('REVOLUT LIMITED', 'REVOLUT LIMITED'), ('XXX', 'XXX')], max_length=50)),
                ('failure_code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=20, null=True)),
                ('internal_note', models.CharField(blank=True, max_length=10, null=True)),
                ('custom_metadata', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_date', models.DateField(auto_now_add=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('execution_date', models.DateTimeField(auto_now_add=True)),
                ('accounting_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to='authentication.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='SEPA3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sender_name', models.CharField(choices=[('---', '---'), ('MIRYA TRADING CO LTD', 'MIRYA TRADING CO LTD'), ('ZAIBATSUS.L.', 'ZAIBATSUS.L.'), ('ELIZABETH GARDEN GROUP S.L.', 'ELIZABETH GARDEN GROUP S.L.'), ('REVSTAR GLOBAL INTERNATIONAL LTD', 'REVSTAR GLOBAL INTERNATIONAL LTD'), ('ECLIPS CORPORATION LTD.', 'ECLIPS CORPORATION LTD.'), ('CDG SYSTEM LTD', 'CDG SYSTEM LTD'), ('BFP FINANCE SERVICE S.L.', 'BFP FINANCE SERVICE S.L.'), ('MOHAMMAD REZA NAJAFI KALASHI', 'MOHAMMAD REZA NAJAFI KALASHI'), ('SERVICES ET PUBLICITÉ ONLINE LTD', 'SERVICES ET PUBLICITÉ ONLINE LTD'), ('XXX', 'XXX')], max_length=255)),
                ('sender_iban', models.CharField(choices=[('---', '---'), ('DE86500700100925993805', 'DE86500700100925993805'), ('ES3901821250410201520178', 'ES3901821250410201520178'), ('ES7901824036500201650056', 'ES7901824036500201650056'), ('GB69BUKB20041558708288', 'GB69BUKB20041558708288'), ('GB43HBUK40127669998520', 'GB43HBUK40127669998520'), ('DE64202208000053288296', 'DE64202208000053288296'), ('ES5868880001643861269006', 'ES5868880001643861269006'), ('DE41400501500154813455', 'DE41400501500154813455'), ('GB33REVO00996939552283', 'GB33REVO00996939552283'), ('XXX', 'XXX')], max_length=34)),
                ('sender_bic', models.CharField(choices=[('---', '---'), ('DEUTDEFFXXX', 'DEUTDEFFXXX'), ('BBVAESMMXXX', 'BBVAESMMXXX'), ('BUKBGB22XXX', 'BUKBGB22XXX'), ('HBUKGB4BXXX', 'HBUKGB4BXXX'), ('SXPYDEHHXXX', 'SXPYDEHHXXX'), ('QNTOESB2XXX', 'QNTOESB2XXX'), ('WELADED1MST', 'WELADED1MST'), ('REVOGB21XXX', 'REVOGB21XXX'), ('XXX', 'XXX')], max_length=11)),
                ('sender_bank', models.CharField(choices=[('---', '---'), ('DEUTSCHE BANK AG', 'DEUTSCHE BANK AG'), ('BANCO BILBAO VIZCAYA ARGENTARIA S.A.', 'BANCO BILBAO VIZCAYA ARGENTARIA S.A.'), ('BARCLAYS BANK UK PLC', 'BARCLAYS BANK UK PLC'), ('HSBC UK BANK PLC', 'HSBC UK BANK PLC'), ('BANKING CIRCLE', 'BANKING CIRCLE'), ('OLINDA SAS SUCURSAL EN ESPAÑA', 'OLINDA SAS SUCURSAL EN ESPAÑA'), ('SPARKASSE MÜNSTERLAND OST', 'SPARKASSE MÜNSTERLAND OST'), ('REVOLUT LIMITED', 'REVOLUT LIMITED'), ('XXX', 'XXX')], max_length=80)),
                ('recipient_name', models.CharField(choices=[('---', '---'), ('MIRYA TRADING CO LTD', 'MIRYA TRADING CO LTD'), ('ZAIBATSUS.L.', 'ZAIBATSUS.L.'), ('ELIZABETH GARDEN GROUP S.L.', 'ELIZABETH GARDEN GROUP S.L.'), ('REVSTAR GLOBAL INTERNATIONAL LTD', 'REVSTAR GLOBAL INTERNATIONAL LTD'), ('ECLIPS CORPORATION LTD.', 'ECLIPS CORPORATION LTD.'), ('CDG SYSTEM LTD', 'CDG SYSTEM LTD'), ('BFP FINANCE SERVICE S.L.', 'BFP FINANCE SERVICE S.L.'), ('MOHAMMAD REZA NAJAFI KALASHI', 'MOHAMMAD REZA NAJAFI KALASHI'), ('SERVICES ET PUBLICITÉ ONLINE LTD', 'SERVICES ET PUBLICITÉ ONLINE LTD'), ('XXX', 'XXX')], max_length=255)),
                ('recipient_iban', models.CharField(choices=[('---', '---'), ('DE86500700100925993805', 'DE86500700100925993805'), ('ES3901821250410201520178', 'ES3901821250410201520178'), ('ES7901824036500201650056', 'ES7901824036500201650056'), ('GB69BUKB20041558708288', 'GB69BUKB20041558708288'), ('GB43HBUK40127669998520', 'GB43HBUK40127669998520'), ('DE64202208000053288296', 'DE64202208000053288296'), ('ES5868880001643861269006', 'ES5868880001643861269006'), ('DE41400501500154813455', 'DE41400501500154813455'), ('GB33REVO00996939552283', 'GB33REVO00996939552283'), ('XXX', 'XXX')], max_length=34)),
                ('recipient_bic', models.CharField(choices=[('---', '---'), ('DEUTDEFFXXX', 'DEUTDEFFXXX'), ('BBVAESMMXXX', 'BBVAESMMXXX'), ('BUKBGB22XXX', 'BUKBGB22XXX'), ('HBUKGB4BXXX', 'HBUKGB4BXXX'), ('SXPYDEHHXXX', 'SXPYDEHHXXX'), ('QNTOESB2XXX', 'QNTOESB2XXX'), ('WELADED1MST', 'WELADED1MST'), ('REVOGB21XXX', 'REVOGB21XXX'), ('XXX', 'XXX')], max_length=11)),
                ('recipient_bank', models.CharField(choices=[('---', '---'), ('DEUTSCHE BANK AG', 'DEUTSCHE BANK AG'), ('BANCO BILBAO VIZCAYA ARGENTARIA S.A.', 'BANCO BILBAO VIZCAYA ARGENTARIA S.A.'), ('BARCLAYS BANK UK PLC', 'BARCLAYS BANK UK PLC'), ('HSBC UK BANK PLC', 'HSBC UK BANK PLC'), ('BANKING CIRCLE', 'BANKING CIRCLE'), ('OLINDA SAS SUCURSAL EN ESPAÑA', 'OLINDA SAS SUCURSAL EN ESPAÑA'), ('SPARKASSE MÜNSTERLAND OST', 'SPARKASSE MÜNSTERLAND OST'), ('REVOLUT LIMITED', 'REVOLUT LIMITED'), ('XXX', 'XXX')], max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('RJCT', 'RJCT'), ('RCVD', 'RCVD'), ('ACCP', 'ACCP'), ('ACTP', 'ACTP'), ('ACSP', 'ACSP'), ('ACWC', 'ACWC'), ('ACWP', 'ACWP'), ('ACCC', 'ACCC'), ('CANC', 'CANC'), ('PDNG', 'PDNG')], default='PDNG', max_length=20)),
                ('execution_date', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
                ('unstructured_remittance_info', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to='authentication.customuser')),
            ],
        ),
    ]
